# Generated by Django 3.0.6 on 2020-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_auto_20200602_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='tag_field',
        ),
        migrations.AddField(
            model_name='snippet',
            name='labels',
            field=models.ManyToManyField(related_name='snippets', to='snippet.Tag'),
        ),
    ]
