# Generated by Django 3.0.6 on 2020-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0004_snippet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('HTML', 'html'), ('CSS', 'css'), ('JAVASCRIPT', 'javascript'), ('PYTHON', 'python')], default='PYTHON', max_length=255),
        ),
    ]
