# Generated by Django 3.0.6 on 2020-06-04 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0005_auto_20200603_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='user',
            new_name='snippet',
        ),
    ]
