# Generated by Django 3.0.6 on 2020-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0007_auto_20200603_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='labels',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code_text',
            field=models.TextField(blank=True, help_text='Type snippet here!', max_length=1000, null=True),
        ),
    ]
